# The URL the site will be built for
base_url = "https://joshhayes.github.io/"

title = "Joshua Hayes"
description = "My website"
compile_sass = true
generate_feeds = true
build_search_index = false

# theme = ""

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
author = "Joshua Hayes"

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Joshua Hayes"

katex_enable = true
katex_auto_render = true
